In [5]:
import pandas as pd


df = pd.read_csv("diabetes_binary_5050split_health_indicators_BRFSS2015.csv", low_memory=False)
df.sample(10)

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
42349,1.0,1.0,1.0,1.0,21.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,4.0,1.0,5.0,0.0,0.0,9.0,6.0,8.0
13916,0.0,0.0,1.0,1.0,36.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,4.0,0.0,0.0,0.0,0.0,6.0,4.0,1.0
5554,0.0,0.0,0.0,1.0,25.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,5.0,5.0,8.0
7175,0.0,0.0,0.0,1.0,25.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,3.0,0.0,0.0,0.0,0.0,6.0,3.0,1.0
66534,1.0,1.0,1.0,1.0,35.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,1.0,0.0,0.0,0.0,9.0,4.0,5.0
2377,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,3.0,0.0,1.0,10.0,5.0,6.0
34237,0.0,1.0,0.0,1.0,25.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,4.0,5.0
5020,0.0,0.0,0.0,1.0,22.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,5.0,6.0,8.0
16236,0.0,0.0,0.0,1.0,25.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,7.0,6.0,8.0
18856,0.0,1.0,0.0,1.0,28.0,0.0,0.0,1.0,1.0,0.0,...,1.0,1.0,4.0,10.0,0.0,0.0,0.0,8.0,5.0,5.0

In [10]:
pd.set_option('display.max_columns', None)

In [20]:
df = pd.read_csv("Speed Dating Data.csv", encoding="latin-1")
df.shape

(8378, 195)

In [23]:
df = pd.read_csv("Credit Score Classification.csv")
df.Credit_Score.unique()

array(['Good', 'Standard', 'Poor'], dtype=object)

In [25]:
df = pd.read_csv("Heart Attack Data Set.csv")
df.sample()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
166,67,1,0,120,229,0,0,129,1,2.6,1,2,3,0