In [43]:
import pandas as pd
import pickle

In [44]:
#codigo para checar em que pasta estamos
import os
current_directory = os.getcwd()
print(current_directory) 


#os.chdir("Path to wherever your file is located")

/Users/Cesar-mac/Desktop/Projeto_dados/main/datasets

In [45]:
df = pd.read_csv("raw/diabetes_binary_5050split_health_indicators_BRFSS2015.csv", low_memory=False,)

In [18]:
df

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70687,1.0,0.0,1.0,1.0,37.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,0.0,0.0,6.0,4.0,1.0
70688,1.0,0.0,1.0,1.0,29.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,2.0,0.0,0.0,1.0,1.0,10.0,3.0,6.0
70689,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,5.0,15.0,0.0,1.0,0.0,13.0,6.0,4.0
70690,1.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
70691,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70692 entries, 0 to 70691
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Diabetes_binary       70692 non-null  float64
 1   HighBP                70692 non-null  uint8
 2   HighChol              70692 non-null  uint8
 3   CholCheck             70692 non-null  uint8
 4   BMI                   70692 non-null  float64
 5   Smoker                70692 non-null  uint8
 6   Stroke                70692 non-null  uint8
 7   HeartDiseaseorAttack  70692 non-null  uint8
 8   PhysActivity          70692 non-null  uint8
 9   Fruits                70692 non-null  uint8
 10  Veggies               70692 non-null  uint8
 11  HvyAlcoholConsump     70692 non-null  uint8
 12  AnyHealthcare         70692 non-null  uint8
 13  NoDocbcCost           70692 non-null  uint8
 14  GenHlth               70692 non-null  float64
 15  MentHlth              70692 non-null  float64
 16  PhysHlth              70692 non-null  float64
 17  DiffWalk              70692 non-null  uint8
 18  Sex                   70692 non-null  uint8
 19  Age                   70692 non-null  float64
 20  Education             70692 non-null  float64
 21  Income                70692 non-null  float64
dtypes: float64(8), uint8(14)
memory usage: 5.3 MB

In [ ]:
#Criação o arquivo pickle com os dados pre processados

In [51]:
## Salva o Dataset como arquivo pickle
output = open('processed/diabetes_binary_5050split_health_indicators_BRFSS2015.pkl', 'wb')
pickle.dump(df, output)
output.close()


#Para abrir
#pkl_file = open('datasets/processed/global-hunger-index.pkl', 'rb')
#mydict2 = pickle.load(pkl_file)
#pkl_file.close()

In [12]:
df.columns

Index(['Diabetes_binary', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

In [42]:
df.memory_usage(deep=True)

Index                      128
Diabetes_binary         565536
HighBP                   70692
HighChol                 70692
CholCheck                70692
BMI                     565536
Smoker                   70692
Stroke                   70692
HeartDiseaseorAttack     70692
PhysActivity             70692
Fruits                   70692
Veggies                  70692
HvyAlcoholConsump        70692
AnyHealthcare            70692
NoDocbcCost              70692
GenHlth                 565536
MentHlth                565536
PhysHlth                565536
DiffWalk                 70692
Sex                      70692
Age                     565536
Education               565536
Income                  565536
dtype: int64

In [49]:
#df = df.drop_duplicates(index, keep='last')
df = df.dropna(subset=['Diabetes_binary'])


colunas = ['HighBP', 'HighChol','CholCheck',  'Smoker','Stroke','HeartDiseaseorAttack', 
            'PhysActivity', 'Fruits', 'Veggies','HvyAlcoholConsump','AnyHealthcare', 
             'NoDocbcCost','DiffWalk', 'Sex']

             
for coluna in colunas:
    #print(coluna)
    df[coluna] = df[coluna].astype('uint8')